Countdown: 5 #The number of seconds players wait until being unfrozen.
MinItems: 3 #The minimum number of items found in a chest.
MaxItems: 10 #The maximum number of items found in a chest.
RarityVariance: 0.2 #The standard deviation of the gaussian function used to modify a chests rarity when being filled with items.